Razor/Models/Conta.cs
namespace Razor.Models
{
    public class Conta
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Razor/Pages/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.Models;
using RestSharp;

namespace Razor.Pages
{
    public class AddModel : PageModel
    {
        [BindProperty]
        public Conta Conta { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = new RestRequest("conta");
                request.AddBody(new
                {
                    name = Conta.Name,
                    description = Conta.Description
                });
                var response = client.ExecutePost(request);
                return RedirectToPage("/Index");
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

Razor/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.Models;
using RestSharp;

namespace Razor.Pages
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public Conta Conta { get; set; }
        public void OnGet(int id = 0)
        {
            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = new RestRequest($"conta/{id}");
                var response = client.ExecuteGet(request);

                Conta contas = Newtonsoft.Json.JsonConvert.DeserializeObject<Conta>(response.Content);

                TempData["contasOne"] = contas;
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public async Task<IActionResult> OnPost(int id)
        {
            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = new RestRequest($"conta/{id}");
                request.AddBody(new
                {
                    name = Conta.Name,
                    description = Conta.Description
                });
                var response = client.ExecutePut(request);
                return RedirectToPage("/Index");
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

Razor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Razor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Razor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json.Nodes;
using System.Text.Json;
using RestSharp;
using Razor.Models;

namespace Razor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet(int id = 0)
        {
            string Baseurl = "http://192.168.1.228:32774/conta";

            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = id == 0 ? new RestRequest("conta") : new RestRequest($"conta/{id}");
                var response = client.ExecuteGet(request);

                List<Conta> contas = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Conta>>(response.Content);

                if (id == 0)
                {
                    TempData["contas"] = contas;
                }
                else
                {
                    TempData["contasOne"] = contas;
                }
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public void OnPostDelete(int id)
        {
            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = new RestRequest($"conta/{id}");
                var response = client.Delete(request);

                OnGet();
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public void OnPostPut(int id)
        {

        }

    }
}

Razor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Razor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Razor/Pages/View.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor.Models;
using RestSharp;

namespace Razor.Pages
{
    public class ViewModel : PageModel
    {
        public void OnGet(int id = 0)
        {
            try
            {
                var client = new RestClient("https://localhost:32774/");
                var request = new RestRequest($"conta/{id}");
                var response = client.ExecuteGet(request);

                Conta contas = Newtonsoft.Json.JsonConvert.DeserializeObject<Conta>(response.Content);

                TempData["contasOne"] = contas;
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

Razor/Pages/Add.cshtml
@page
@model Razor.Pages.AddModel
@{
}

@{
    ViewData["Title"] = "Cadastrar";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar nova conta</h1>
    <form method="post">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nome</label>
            <input asp-for="Conta.Name" type="name" class="form-control" id="exampleFormControlInput1" placeholder="Nome" />
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descrição</label>
            <input asp-for="Conta.Description" type="description" class="form-control" id="exampleFormControlInput1" placeholder="Descrição">
        </div>
        <button type="submit" asp-page-handler="post" class="btn btn-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
            </svg>
            Salvar
        </button>
    </form>
</div>

Razor/Pages/Edit.cshtml
@page "{id:int}"
@using Razor.Models;
@model Razor.Pages.EditModel

@{
    ViewData["Title"] = "Editar";
    Conta contasOne = (Conta)TempData["contasOne"];
}

<div class="text-center">
    <h1 class="display-4">Editar conta</h1>
    <p>@contasOne.Id - @contasOne.Name</p>
    <form method="post">
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nome</label>
            <input asp-for="Conta.Name" type="name" class="form-control" id="exampleFormControlInput1" placeholder="@contasOne.Name" value="@contasOne.Name" />
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descrição</label>
            <input asp-for="Conta.Description" type="description" class="form-control" id="exampleFormControlInput1" placeholder="@contasOne.Description" value="@contasOne.Description">
        </div>
        <button type="submit" asp-page-handler="post" asp-route-id="@contasOne.Id" class="btn btn-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
            </svg>
            Salvar
        </button>
    </form>
</div>

Razor/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Components.Web;
@using Razor.Models;
@using RestSharp;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    List<Conta> dados1 = (List<Conta>)TempData["contas"];
    List<Conta> dadosOne = (List<Conta>)TempData["contasOne"];
}

<div class="text-center">
    <h1 class="display-4">Lista de Contas</h1>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var conta in dados1)
        {
            <tr>
                <th>@conta.Id</th>
                <td>@conta.Name</td>
                <td>@conta.Description</td>
                <form method="post">
                <th scope="col">
                    <a asp-page="./View" asp-route-id="@conta.Id" class="btn btn-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                        </svg>
                        Ver
                    </a>
                    <a asp-page="./Edit" asp-route-id="@conta.Id" class="btn btn-success">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                        </svg>
                        Editar
                    </a>
                    <button type="submit" asp-page-handler="delete" asp-route-id="@conta.Id" class="btn btn-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z" />
                            <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z" />
                        </svg>
                        Excluir
                    </button>
                </th>
                </form>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <a asp-page="./Add" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-add" viewBox="0 0 16 16">
            <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
            <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z" />
        </svg>
        Criar nova conta
    </a>
</div>

@section scripts{

    <script type="text/javascript">
        function Delete() {
            //$.get("/Home/GetMessage", function (data) {
            //    $("p").html(data);
            //});
            alert("ok")
        }




    </script>

}

Razor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Razor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Razor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Razor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Razor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Razor/Pages/View.cshtml
@page
@using Razor.Models;
@model Razor.Pages.ViewModel
@{
    ViewData["Title"] = "Ver";
    Conta contasOne = (Conta)TempData["contasOne"];
}

<div class="text-center">
    <h1 class="display-4">Visualizar conta</h1>

    <div class="card" style="width: 18rem;">
        <img src="https://simpleicon.com/wp-content/uploads/account.png" class="card-img-top" alt="@contasOne.Name">
        <div class="card-body">
            <h5 class="card-title">@contasOne.Id - @contasOne.Name</h5>
            <p class="card-text">@contasOne.Description</p>
            <a asp-page="./Edit" asp-route-id="@contasOne.Id" class="btn btn-primary">Editar</a>
        </div>
    </div>
</div>